application: polymer-project
version: 20131217
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "0s"

libraries:
- name: PIL
  version: latest

#inbound_services:
#- warmup

handlers:

# Top-level URLs ---------------------------------------------------------------
- url: /$
  static_files: _site/index.html
  upload: _site/index\.html

- url: /build/$
  static_files: _site/build/index.html
  upload: _site/build/index\.html

- url: /build/(.*)
  script: build.application

# Short URLs -------------------------------------------------------------------
- url: /platform(.min)?.js
  static_files: _site/components/platform/platform.js
  upload: _site/components/platform/platform\.js

- url: /platform(.min)?.js.map
  static_files: _site/components/platform/platform.js.map
  upload: _site/components/platform/platform\.js.\map

- url: /polymer(.min)?.js
  static_files: _site/components/polymer/polymer.js
  upload: _site/components/polymer/polymer\.js

- url: /polymer(.min)?.js.map
  static_files: _site/components/polymer/polymer.js.map
  upload: _site/components/polymer/polymer\.js\.map
# ------------------------------------------------------------------------------

# Map minified polymer to minified version.
# This also preservers old URL (/polymer/polymer.min.js)
# COMMENT OUT TO TEST UNIMINIFIED Polymer
#- url: /(polymer-all\/)?polymer/polymer(.min)?.js
#  static_files: _site/polymer-all/components/polymer/polymer.js
#  upload: _site/polymer-all/components/polymer/polymer\.js

# / Elements -------------------------------------------------------------------
- url: /(polymer|polymer-ui|more)-elements/(.*)
  static_files: _site/polymer-all/\1-elements/\2
  upload: _site/polymer-all/(polymer|polymer-ui|more)-elements/(.*)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(toolkit-ui|web-animations-js)/(.*)
  static_files: _site/polymer-all/\1/\2
  upload: _site/polymer-all/(toolkit-ui|web-animations-js)/(.*)
  http_headers:
    Access-Control-Allow-Origin: "*"

# /tools -----------------------------------------------------------------------
  #curl https://polymer-project.org/tools/pull-all.sh | bash
#- url: /tools/pull-all\.sh$
#  static_files: _site/polymer-all/tools/bin/pull-all.sh
#  upload: _site/polymer-all/tools/bin/pull-all\.sh

- url: /tools/sandbox/$
  static_files: _site/polymer-all/projects/sandbox/index.html
  upload: _site/index\.html

- url: /tools/sandbox/(.*)
  static_files: _site/polymer-all/projects/sandbox/\1
  upload: _site/(.*)/index.html

# Map raw paths with trailing "/" to an index.html file.
- url: /(.*)/$
  static_files: _site/\1/index.html
  upload: _site/(.*)/index.html

# ADD TO TEST unminified Polymer 
# - url: /polymer-all
#   static_dir: _site/polymer-all
#   http_headers:
#     Access-Control-Allow-Origin: "*"

# New mappings for Bower
- url: /components
  static_dir: _site/components
  http_headers:
    Access-Control-Allow-Origin: "*"

# All other URLs map directly to their path in _site/.
- url: /
  static_dir: _site
  http_headers:
    Access-Control-Allow-Origin: "*"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?third_party/closure/.*
- ^polymer-all/.*
- ^scripts/.*

# few extras to reduce number of files uploaded.
- ^(.*/)?.*\.sublime-project
- ^(.*/)?.*\.sublime-workspace
- ^(.*/)?platform-dev/workbench/.*
- ^(.*/)?(AUTHORS|LICENSE|PATENTS|COPYING)$
